/** Canonical error codes used across the API */
export const ERROR_CODES = {
  // Auth
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  USER_DISABLED: 'USER_DISABLED',
  AUTH_FAILED: 'AUTH_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  USE_ACCEPT_INVITE: 'USE_ACCEPT_INVITE',
  USE_VERIFY: 'USE_VERIFY',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Database
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  NOT_FOUND: 'NOT_FOUND',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  DATABASE_ERROR: 'DATABASE_ERROR',
  PRISMA_VALIDATION_ERROR: 'PRISMA_VALIDATION_ERROR',

  // Leads
  LEAD_ALREADY_CONVERTED: 'LEAD_ALREADY_CONVERTED',
  REQUIRES_USER_ACCOUNT: 'REQUIRES_USER_ACCOUNT',
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',

  // Students
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  INVALID_STAGE_TRANSITION: 'INVALID_STAGE_TRANSITION',

  // Documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  UPLOAD_NOT_COMPLETED: 'UPLOAD_NOT_COMPLETED',

  // Chat
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_ENDED: 'SESSION_ALREADY_ENDED',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  REQUEST_ERROR: 'REQUEST_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
